from langchain_core.messages import SystemMessage, HumanMessage, AIMessage, ToolMessage

from ..config import llm_from_axis 
from ..memory_LLMs_schema import AgentState
from ..tools import api_query_base_on_name

# Node 1: itemId retrieve Agent
def itemId_retrieve_agent(state: AgentState) -> AgentState:
    """Retrieve itemId based on product name from user input and return the itemId."""
    
    llm = llm_from_axis
    
    # augment the llm with tools
    llm_with_tools = llm.bind_tools([api_query_base_on_name])
    
    user_input = state["messages"][-1].content # comes from the agent state, which is the original user input(short-term memory)
    
   
    system_message = """
    Role: You are an intelligent product information assistant for Axis Communications products.

    Your task when a user asks about a product:

    Step 1 - IDENTIFY the product name/model number from the user's question:
    - Look for AXIS product codes (e.g., "Q6074-E", "M5000", "T8127")
    - Product names may appear with or without "AXIS" prefix
    - Common patterns: "AXIS [MODEL]", just "[MODEL]", "AXIS [SERIES] [MODEL]"

    Step 2 - EXTRACT the clean product identifier:
    - Remove extra words but keep the core model identifier
    - Examples:
        * "compatible with Q6074-E" → extract "Q6074-E"
        * "tell me about AXIS M5000" → extract "AXIS M5000" or "M5000"
        * "accessories for the T8127 camera" → extract "T8127"

    Step 3 - USE the tool:
    - Call api_query_base_on_name with the extracted product name
    - The tool will return the itemId

    Step 4 - RESPOND helpfully:
    - Inform the user about the found itemId in a friendly way
    - Format: "The itemId for [product name] is: [itemId]"
    
    Remember: If you cannot identify a product name, ask the user to clarify.
    """

    response = llm_with_tools.invoke([
        SystemMessage(content=system_message),
        HumanMessage(content=user_input)
    ])

    # Check if the agent decided to call the tool (this is a feature of the augmented LLM, which can call tools when it thinks it's necessary)
    if response.tool_calls:

        print("ItemId Retrieve Agent decided to use the tool with input:", response.tool_calls[0]["args"])
        print(f"ItemId Retrieve Agent decided to use the tool: {response.tool_calls[0]['name']}")

        # Manual execute the tool
        tool_result = api_query_base_on_name.invoke(response.tool_calls[0]["args"])
        print(f"Tool result: {tool_result}")
        
    
        messages = [
            SystemMessage(content=system_message),
            HumanMessage(content=user_input),
            response,  
            ToolMessage(
                content=str(tool_result),
                tool_call_id=response.tool_calls[0]["id"] # eusure the tool result is associated with the correct tool call
            )
        ]
        
        # Second time to invoke the LLM with the tool result, to get the final answer for the user
        final_response = llm.invoke(messages)
        answer = final_response.content
    
    else:
        # no tool calling, directly return the response from the agent
        # this means the final answer is purly generated by the LLM
        answer = llm.invoke([
            SystemMessage(content=system_message),
            HumanMessage(content=user_input)
        ]).content
        
    print(f"ItemId Retrieve Agent Result: {answer}")
    
    return {
        **state,
        "final_answer": answer
    }
